### ISSUE TITLE
do a feature audit between studiorack and owlplug

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-core#7]

**Comment by kmturley** [comment]
Conducted a feature audit here:
https://docs.google.com/document/d/1mlRZz_ypqoB_SmXmf0bDANZdcPZ4woBNLy052RD8u1c/edit?usp=sharing

**Comment by RustoMCSpit** [comment]
@kmturley should this repo be deprecated like the studiorack registry one?-

**Comment by kmturley** [comment]
It will be, once I have rewritten all of the code into the new package!
